#!/bin/bash

eval `grep '^#define FIRMWARE_' src/fd_hal_system.c | sed -e 's/#define FIRMWARE_\([MP][^ ]*\) \(.*\)/\1=\2/' | tr '[:upper:]' '[:lower:]'`
echo releasing version $major.$minor.$patch

cp "THUMB Flash Release/FireflyIce/FireflyIce.hex" ../firefly-ice-api/FireflyDevice/FireflyDevice
echo "#! {\"major\":$major, \"minor\":$minor, \"patch\":$patch, \"note\":\"beta\", \"address\":\"0x08000\", \"length\":\"0x38000\"}" >> ../firefly-ice-api/FireflyDevice/FireflyDevice/FireflyIce.hex

dst=../firefly-ice-api/Windows/FireflyDevice/FDResource.cpp
cat << EOF > $dst
// This file is automatically generated by firefly-ice-api/release.bash

#include "FDResource.h"

#include <exception>
#include <string>

namespace FireflyDesign {

static const char FireflyIce_hex[] = {
EOF
cat "THUMB Flash Release/FireflyIce/FireflyIce.hex" | xxd -include >> $dst
echo ',' >> $dst
echo "#! {\"major\":$major, \"minor\":$minor, \"patch\":$patch}" | xxd -include >> $dst
cat << EOF >> $dst
};

std::string FDResource::stringWithContentsOfResource(std::string resource) {
    if (resource == "FireflyIce.hex") {
        return std::string(FireflyIce_hex, FireflyIce_hex + sizeof(FireflyIce_hex));
    }
    throw std::exception("resource not found");
}

}
EOF

cp "THUMB Flash Release/FireflyBoot/FireflyBoot.elf" ../firefly-production-tools/FireflyTool/FireflyTool
cp "THUMB Flash Release/FireflyIce/FireflyIce.elf" ../firefly-production-tools/FireflyTool/FireflyTool
cp "THUMB RAM Debug/FireflyRadioTest/FireflyRadioTest.elf" ../firefly-production-tools/FireflyTool/FireflyTool
cp "THUMB RAM Debug/FireflyUsbTest/FireflyUsbTest.elf" ../firefly-production-tools/FireflyTool/FireflyTool
cp "THUMB RAM Debug/FireflyIceTest/FireflyIceTest.elf" ../firefly-production-tools/FireflyTool/FireflyTool

cp "THUMB RAM Debug/FireflyFlash/FireflyFlash.elf" ../firefly-production-tools/FireflyProduction/FireflyProduction/FireflyFlashEFM32.elf
cp "FireflyFlashSTM32F4 THUMB Debug/FireflyFlashSTM32F4.elf" ../firefly-production-tools/FireflyProduction/FireflyProduction/
cp "FireflyFlashNRF51 THUMB Debug/FireflyFlashNRF51.elf" ../firefly-production-tools/FireflyProduction/FireflyProduction/
