#ifndef FDI_RELAY_H
#define FDI_RELAY_H

#include "fdi_gpio.h"

#define FDI_RELAY_IOA0 FDI_GPIO_IOA0
#define FDI_RELAY_IOA1 FDI_GPIO_IOA1
#define FDI_RELAY_IOA2 FDI_GPIO_IOA2
#define FDI_RELAY_IOA3 FDI_GPIO_IOA3
#define FDI_RELAY_IOA4 FDI_GPIO_IOA4
#define FDI_RELAY_IOA5 FDI_GPIO_IOA5
#define FDI_RELAY_IOA6 FDI_GPIO_IOA6
#define FDI_RELAY_IOA7 FDI_GPIO_IOA7
#define FDI_RELAY_IOR0 FDI_GPIO_IOR0
#define FDI_RELAY_IOR1 FDI_GPIO_IOR1
#define FDI_RELAY_IOR2 FDI_GPIO_IOR2
#define FDI_RELAY_IOR3 FDI_GPIO_IOR3

#define FDI_RELAY_ATE_USB_5V_EN     FDI_GPIO_ATE_USB_5V_EN
#define FDI_RELAY_ATE_USB_D_EN      FDI_GPIO_ATE_USB_D_EN
#define FDI_RELAY_ATE_BATTERY_SENSE FDI_GPIO_ATE_BATTERY_SENSE
#define FDI_RELAY_ATE_BUTTON_EN     FDI_GPIO_ATE_BUTTON_EN
#define FDI_RELAY_ATE_MCU_VCC_SENSE FDI_GPIO_ATE_MCU_VCC_SENSE
#define FDI_RELAY_ATE_FILL_EN       FDI_GPIO_ATE_FILL_EN
#define FDI_RELAY_ATE_DRAIN_EN      FDI_GPIO_ATE_DRAIN_EN
#define FDI_RELAY_ATE_BAT_CAP_EN    FDI_GPIO_ATE_BAT_CAP_EN
#define FDI_RELAY_ATE_BAT_ADJ_EN    FDI_GPIO_ATE_BAT_ADJ_EN

void fdi_relay_initialize(void);

void fdi_relay_set(uint32_t identifier, bool value);
void fdi_relay_on(uint32_t identifier);
void fdi_relay_off(uint32_t identifier);

#endif
