#ifndef FD_CONTROL_CODES_H
#define FD_CONTROL_CODES_H

#define FD_CONTROL_SYNC_START 1
#define FD_CONTROL_SYNC_DATA 2
#define FD_CONTROL_SYNC_ACK 3

#define FD_CONTROL_GET_PROPERTIES 4
#define FD_CONTROL_SET_PROPERTIES 5

#define FD_CONTROL_PROVISION 6
#define FD_CONTROL_RESET 7

#define FD_CONTROL_PROPERTY_VERSION    0x00000001
#define FD_CONTROL_PROPERTY_DEBUG_LOCK 0x00000002
#define FD_CONTROL_PROPERTY_RTC        0x00000004
#define FD_CONTROL_PROPERTY_POWER      0x00000008
#define FD_CONTROL_PROPERTY_SITE       0x00000010

#endif